config/routes.rb
Entrydns::Application.routes.draw do

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  devise_for :admins

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope module: 'users' do

    resources :authentications do
      as_routes
    end

    resources :domains do
      as_routes
    end

    resources :hosts do
      as_routes
      member do
        put 'new_token'
      end
    end

    match '/records/modify/:authentication_token', to: 'records#modify',
      as: :modify_record, via: [:get, :post, :put]
    resources :records do
      as_routes
    end

    resources :soas do
      as_routes
    end

    resources :ns do
      as_routes
    end

    resources :mxes do
      as_routes
    end

    resources :as do
      as_routes
      member do
        put 'new_token'
      end
    end

    resources :cnames do
      as_routes
    end

    resources :txts do
      as_routes
    end

    resources :aaaas do
      as_routes
    end

    resources :srvs do
      as_routes
    end

    resources :permissions do
      as_routes
    end

  end

  scope module: 'public' do

    resources :pages, only: :show, path: ''
    post 'contact', to: 'pages#contact'

    root to: 'pages#show', id: 'home'

  end

end

app/views/shared/navigation/_public.html.erb
<% semantic_navigation :public_nav, html: { class: 'nav navbar-nav' } do |n| %>
  <%= n.item '', link: page_path('about') do %>
    <i class="glyphicon glyphicon-info-sign"></i> About
  <% end %>
  <%= n.item '', link: page_path('team') do %>
    <i class="glyphicon glyphicon-user"></i> Team
  <% end %>
  <%= n.item '', link: page_path('contact') do %>
    <i class="glyphicon glyphicon-envelope"></i> Contact
  <% end %>
  <%= n.item '', link: page_path('help') do %>
    <i class="glyphicon glyphicon-question-sign"></i> Help & Support
  <% end %>
<% end %>

<% semantic_navigation :session_nav, html: { class: 'nav navbar-nav navbar-right' } do |n| %>
  <%= n.item '', link: Settings.news_link, 
    html: { rel: 'tooltip', data: { placement: 'bottom' }, title: Settings.news_link } do %>
    <i class="glyphicon glyphicon-share-alt"></i> News
  <% end %>
  <%= n.item '', link: page_path('donate'),
    html: { rel: 'tooltip', title: 'PayPal', data: { placement: 'bottom' }, class: 'highlight' } do %>
    <i class="glyphicon glyphicon-heart"></i> Donate
  <% end %>
  <%= n.item '', link: new_user_registration_path do %>
    <i class="glyphicon glyphicon-arrow-up"></i> Sign up
  <% end %>
  <%= n.item '', link: new_user_session_path do %>
    <i class="glyphicon glyphicon-arrow-right"></i> Sign in
  <% end %>
<% end %>

app/views/shared/navigation/_users.html.erb
<% semantic_navigation :application_nav, html: { class: 'nav navbar-nav' } do |n| %>
  <%= n.item '', link: domains_path do %>
    <i class="glyphicon glyphicon-th-list"></i> My Domains
  <% end %>
  <%= n.item '', link: hosts_path do %>
    <i class="glyphicon glyphicon-th"></i> Dynamic Hosts
  <% end %>
  <%= n.item '', link: page_path('help') do %>
    <i class="glyphicon glyphicon-question-sign"></i> Help & Support
  <% end %>
<% end %>

<% semantic_navigation :user_nav, html: { class: 'nav navbar-nav navbar-right' } do |n| %>
  <%= n.item '', link: Settings.news_link, 
    html: { rel: 'tooltip', data: { placement: 'bottom' }, title: Settings.news_link } do %>
    <i class="glyphicon glyphicon-share-alt"></i> News
  <% end %>
  <%= n.item '', link: page_path('donate'),
    html: { rel: 'tooltip', title: 'PayPal', data: { placement: 'bottom' }, class: 'highlight' } do %>
    <i class="glyphicon glyphicon-heart"></i> Donate
  <% end %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-user"></i> <%= current_user.email %> <b class="caret"></b>
      </a>
      <%= n.group do %>
        <%= n.item '', link: edit_user_registration_path, html: { rel: 'tooltip', title: "IP: #{client_remote_ip}" } do %>
          <i class="glyphicon-cog"></i> Settings
        <% end %>
        <%= n.item '', link: destroy_user_session_path do %>
          <i class="glyphicon-off"></i> Sign out
        <% end %>
      <% end %>
    </li>
<% end %>